#!/bin/bash
cd /tmp

curl -O https://blackarch.org/strap.sh

# verify script with blackarch itself
echo 26849980b35a42e6e192c6d9ed8c46f0d6d06047 strap.sh | sha1sum -c

chmod +x strap.sh
bash -c strap.sh
